theme: jekyll-theme-minimal
title: What makes a movie succesful?
description: The purpose of this website is to show the results of the applied data analysis study that has been carried out by TheADAholics group to determine what factors make a successful film.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
