remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: jekyll-theme-minimal
title: What makes a movie succesful?
description: The purpose of this website is to show the results of the applied data analysis study that has been carried out by TheADAholics group to determine what factors make a successful film.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
